apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: app 
        image: app-image:latest
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: secret-key
