name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up HashiCorp Vault
        uses: hashicorp/setup-vault@v2
        with:
          vault_version: '1.11.0'

      - name: Retrieve secrets from Vault
        id: vault
        run: |
          vault kv get -field=my-secret kv/my-secret-path > secret.txt
        
      - name: Build and Test
        run: |
          echo "Building and testing..."
